### ISSUE TITLE
conversion fails on a project already using typescript

### ISSUE THREAD

**Issue by mispp** [lamualfa/setup-routify-ts#1]
steps to reproduce
1. setup a typescript svelte project
```
npx degit sveltejs/template svelte-typescript-app
cd svelte-typescript-app
node scripts/setupTypeScript.js
```

2. install routify
`npm i -D @sveltech/routify`

3. run conversion script for routify
`npx setup-routify-ts convert`

**Comment by lamualfa** [comment]
`setup-routify-ts` only work for [Routify Starter Template](https://github.com/roxiness/routify-starter), not for [Svelte Template](https://github.com/sveltejs/template).
