### ISSUE TITLE
Doesn't work with the new roxi version 

### ISSUE THREAD

**Issue by flymedllva** [lamualfa/setup-routify-ts#2]
https://github.com/roxiness/routify-starter

**Comment by rommyarb** [comment]
The error says:
```
ENOENT: no such file or directory, open '/Users/[username]/my-routify-project/scripts/base.config.js'
```

**Comment by lamualfa** [comment]
Has been fixed in the `2` version. See [v2.0.0](https://github.com/lamualfa/routify-ts/releases/tag/v2.0.0). Thanks.
