### ISSUE TITLE
$isActive reports wrong types

### ISSUE THREAD

**Issue by Abourass** [lamualfa/setup-routify-ts#7]
Using the isActive helper as expected:
`$isActive('./settings', true)`

You get the following error: 
`Argument of type 'boolean' is not assignable to parameter of type '{ [x: string]: any; }'.ts(2345)`

**Comment by LumaKernel** [comment]
I confirmed the documentation for Routify v2 is outdated, you should use `$isActive('./settings', undefined, {strict: true})`.
[more info](https://github.com/roxiness/routify/blob/94823fecb267549e86675429fc679ba2dc49e02f/runtime/helpers.js#L346-L351)
